import React, {useEffect, useState} from 'react';
import './styles/App.css';
import twitterLogo from './assets/twitter-logo.svg';
import { ethers } from "ethers";


// Constants
const TWITTER_HANDLE = 'DsouzaJovian';
const TWITTER_LINK = `https://twitter.com/${TWITTER_HANDLE}`;

const App = () => {

  const [currentAccount, setCurrentAccount] = useState("");
  
  const checkIfWalletIsConnected =  async () => {
    const { ethereum } = window;
    if(!ethereum){
      console.log("Make sure you have metamask");
      return;
    }
    else{
      console.log("We have a ethereum object", ethereum);
    }

    const accounts = await ethereum.request({method: 'eth_accounts'});

    if(accounts.length != 0){
      const account = accounts[0]
      console.log("Found an authorized account", account);
      setCurrentAccount(account);
    }
    else{
      console.log("Could not find authorized account");
    }
  }

  const connectWallet = async () => {
    try{
      const {ethereum} = window;
      if(!ethereum){
        console.log("Get Metamask");
        return;
      }
      const accounts = await ethereum.request({method: 'eth_requestAccounts'});
      setCurrentAccount(accounts[0]);
    }
    catch(error) {
      console.log(error);
    }
  }

  // Render Methods
  const renderNotConnectedContainer = () => (
    <button onClick={connectWallet} className="cta-button connect-wallet-button">
      Connect to Wallet
    </button>
  );

  useEffect(() => {
    checkIfWalletIsConnected();
  }, [])

  return (
    <div className="App">
      <div className="app-container">
        <div className="header-container">
          {/* <p className="header gradient-text">Stable Diffusion NFT</p> */}
          <p className="sub-text">
            Create, Collect and Sell creative NFTs generated by <b>AI</b>
          </p>
          {currentAccount === "" ? (
            renderNotConnectedContainer()
          ) : (
            <button className="cta-button connect-wallet-button">
              Mint NFT
            </button>
          )}
        </div>
        <div className="footer-container">
          <img alt="Twitter Logo" className="twitter-logo" src={twitterLogo} />
          <a
            className="footer-text"
            href={TWITTER_LINK}
            target="_blank"
            rel="noreferrer"
          >{`built on @${TWITTER_HANDLE}`}</a>
        </div>
      </div>
    </div>
  );
};

export default App;